version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - fastapi_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge