FROM python:3.12.0-alpine3.18

RUN apk add --no-cache gcc musl-dev rust cargo

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools wheel

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]

#uvicorn app:app --reload  